-- MySQL Script generated by MySQL Workbench
-- Tue Nov 30 14:34:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rsg
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rsg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rsg` DEFAULT CHARACTER SET utf8 ;
USE `rsg` ;

-- -----------------------------------------------------
-- Table `rsg`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsg`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rsg`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsg`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `content` VARCHAR(255) NULL,
  `created` DATETIME NULL,
  `online` INT NULL,
  `type` VARCHAR(255) NULL,
  `slug` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_message_users1_idx` (`user_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rsg`.`medias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rsg`.`medias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `file` VARCHAR(255) NULL,
  `message_id` INT NULL,
  `type` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_medias_message_idx` (`message_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
